import moana from "../asset/moanas.webp";
import venom from "../asset/venom.jpg";

export const pinTabs = [
  {
    title: "We are a fast food delivery service scaled to meet your need",
    paragraph: "WHO WE ARE",
    intro: "Freshly Baked Daily",
    paragraph2:
      "Enjoy the assurance of freshly baked treats every day. We partner with local bakeries to bring you warm, just-out-of-the-oven goodies, ensuring every bite is a delight.",
  },
  {
    title: "We are a fast food delivery service scaled to meet your need",
    paragraph: "WHO WE ARE",
    intro: "No More Waiting",
    paragraph2:
      "Say goodbye to long lines and waiting times. Order from your favorite bakeries with our app, and we'll have your baked goods prepared and delivered to you promptly.",
  },
  {
    title: "We are a fast food delivery service scaled to meet your need",
    paragraph: "WHO WE ARE",
    intro: "Wide Variety of Choices",
    paragraph2:
      "Explore a wide range of baked delights, from classic croissants to indulgent pastries. Our app offers a diverse menu, so you can satisfy your cravings with something new or stick to your favorites.",
  },
];

export const itemOne = [
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
];

export const itemTwo = [
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
];
export const itemThree = [
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
  {},
];

export const MOVIES_TO_WATCH = [
  {
    name: "Moana Part 2",
    download_links: [
      "https://poawooptugroo.com/4/8899412",
      "https://poawooptugroo.com/4/8899412",
      "https://tfpdl.se/moana-2-2024-proper-2160p-web-dl-dd5-1-x265-tfpdl/",
      "https://moviebox.ng/movies/moana-2-C1roud60JE4?id=3908506583235477456&scene=&type=/movie/detail",
    ],
    image: moana,
    id: "moana-part-2",
    brief_intro:
      "In this thrilling sequel, Moana faces a formidable new challenge when the Coconut Kingdom, a militant tribe descended from the Kakamora, threatens Motunui’s peace. Armed with armored coconut hulls and razor-sharp projectiles, they seek an ancient artifact hidden on Moana’s island, believing it holds the power to restore their barren lands. As tensions escalate into explosive naval battles, Moana and Maui navigate treacherous waters, uncovering the Kingdom’s desperation—a cursed blight withering their coconut groves. Blending courage with empathy, Moana devises a daring plan: unite both tribes to reignite the heart of Te Fiti, healing the land and bridging their divide. With dynamic oceanic clashes, Maui’s shapeshifting prowess, and themes of unity over conflict, the adventure culminates in a pact of shared stewardship, proving that understanding and cooperation are the greatest strengths of all.",
  },
  {
    name: "Venom The Last Dance 2024",
    download_links: [
      "https://poawooptugroo.com/4/8899412",
      "https://poawooptugroo.com/4/8899412",
      "https://v.moviebox.ng/qV451p0llX8",
      "https://tfpdl.se/?s=venom+the+last+dance",
    ],
    image: venom,
    id: "venom-last-dance",
    brief_intro:
      "Venom: The Last Dance (2024) races into chaos as Eddie Brock and his alien alter-ego, Venom, become fugitives hunted by a lethal alliance of global militaries and symbiote overlords. With nowhere to hide, their desperate fight for survival collides with the cosmic horror of Knull, the primordial deity of the symbiote hive, who descends to annihilate all life. The film ignites with relentless stakes: high-octane chases through neon-lit cities, visceral symbiote-on-symbiote brawls that reshape skylines, and a wildly inventive showdown where Venom possesses a galloping horse to trample enemies in a midnight cavalry charge. As bonds fray and loyalties shatter, Eddie and Venom confront their twisted partnership in a shattering climax that forces a heart-wrenching choice—one that will redefine their destiny forever. Packed with dark humor, jaw-dropping spectacle, and a poignant farewell, The Last Dance delivers a thunderous, emotional crescendo to the duo’s chaotic saga.",
  },
  {
    name: "What IF Season 3",
    download_links: ["", "", ""],
    image: "",
    id: "3",
    brief_intro: "",
  },
  {
    name: "Lord of the ring, Rings of power",
    download_links: ["", "", ""],
    image: "",
    id: "4",
    brief_intro: "",
  },
];
